Feature gamemode
mcDoggyKiip/DoggyCraftSite pull request #2
Opened 2020-07-13 19:37 UTC by mcDoggyKiip

### Description
Major update on the server gamemodes:
- make gamemodes editable
- add an easy way to add gamemodes (on the site)
- added description that will be displayed
- display a nice ribbon on gamemodes that are newer than 1 month
### Important Information
Update of the Database is required!

2020-07-14 14:04 UTC, ionianthales requested changes

2020-07-14 14:04 UTC, ionianthales commented on app/Http/Controllers/GamemodeController.php
> +    }
this show function's parameter needs to be `Gamemode $gamemode` to use Laravel's implicit binding.
and remove
`$gamemode = Gamemode::all()->where('id', '==', $id)->first();`

2020-07-14 14:04 UTC, ionianthales commented on app/Http/Controllers/GamemodeController.php
> +                $gamemode = Gamemode::all()->where('id', '==', $id)->first();
here also, you could put `Gamemode $gamemode` instead $id for the parameter.

2020-07-14 14:04 UTC, ionianthales commented on app/Http/Controllers/GamemodeController.php
> +                $gamemode = Gamemode::findOrFail($id);
Instead using `findOrFail` function, you could just put `Gamemode $gamemode` for the parameter `$id`.

check this guide, [https://mattstauffer.com/blog/implicit-model-binding-in-laravel-5-2/](url)

2020-07-14 14:04 UTC, ionianthales commented on app/Http/Controllers/GamemodeController.php
> +}
here same thing, `Gamemode $gamemode` instead `$id`

2020-07-14 17:14 UTC, mcDoggyKiip commented
@ionianthales you've got a point in using the implicit-binding of the model, however try to refer to the latest of laravels own documentation: https://laravel.com/docs/7.x/routing#implicit-binding

2020-07-15 08:24 UTC, ionianthales requested changes

2020-07-15 08:24 UTC, ionianthales commented on app/Http/Controllers/GamemodeController.php
> +    }
Aside from the style (I recommend you take a look at PHP Cs Fixer), why are you transforming your Gamemode entries? Is this an API? If not, you can just pass the models as-is to the view
And if it's an API, you should use API resources instead https://laravel.com/docs/7.x/eloquent-resources#introduction
Also, instead of a foreach loop, you can just use Laravel's collections to transform your data, since Eloquent is returning a collection
So, either https://laravel.com/docs/7.x/collections#method-transform or https://laravel.com/docs/7.x/collections#method-map

2020-07-15 09:21 UTC, mcDoggyKiip commented on app/Http/Controllers/GamemodeController.php
> +    }
I don't know what i did there, but it's certainly not right.
Fixed in the new commit.

2020-07-15 09:39 UTC, ionianthales approved these changes
I am okay with this code!

2020-07-15 09:39 UTC, merged